---
- name: Install BIND packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
  tags: [install]

- name: Create zones directory
  ansible.builtin.file:
    path: "{{ zones_folder }}"
    state: directory
    owner: bind
    group: bind
    mode: "0755"
  tags: [install]
