---
- name: Install BIND packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ bind_packages }}"
  tags: [install]

- name: Create zones directory
  ansible.builtin.file:
    path: "{{ zones_folder }}"
    state: directory
    owner: "{{ bind_user }}"
    group: "{{ bind_group }}"
    mode: "0755"
  tags: [install]
