---
- name: Configure MASTER | named.conf.options
  ansible.builtin.template:
    src: master/named.conf.options.j2
    dest: "{{ bind_config_path }}/named.conf.options"
    owner: root
    group: "{{ bind_group }}"
    mode: "0644"
  notify: Reload bind
  tags: [configure]

- name: Configure MASTER | named.conf.local
  ansible.builtin.template:
    src: master/named.conf.local.j2
    dest: "{{ bind_config_path }}/named.conf.local"
    owner: root
    group: "{{ bind_group }}"
    mode: "0644"
  notify: Reload bind
  tags: [configure]

- name: Configure MASTER | forward zone
  ansible.builtin.template:
    src: master/forwards.j2
    dest: "{{ zones_folder }}/{{ zones.forwards }}"
    owner: root
    group: "{{ bind_group }}"
    mode: "0644"
  notify: Reload bind
  tags: [configure]

- name: Configure MASTER | reverse zone
  ansible.builtin.template:
    src: master/revers.j2
    dest: "{{ zones_folder }}/{{ zones.revers }}"
    owner: root
    group: "{{ bind_group }}"
    mode: "0644"
  notify: Reload bind
  tags: [configure]
