---
- name: Configure MASTER | named.conf.options
  ansible.builtin.template:
    src: master/named.conf.options.j2
    dest: "/etc/bind/named.conf.options"
    owner: root
    group: bind
    mode: "0644"
  notify: Restart bind9
  tags: [configure]

- name: Configure MASTER | named.conf.local
  ansible.builtin.template:
    src: master/named.conf.local.j2
    dest: "/etc/bind/named.conf.local"
    owner: root
    group: bind
    mode: "0644"
  notify: Restart bind9
  tags: [configure]

- name: Configure MASTER | forward zone
  ansible.builtin.template:
    src: master/forwards.j2
    dest: "/etc/bind/zones/{{ zones.forwards }}"
    owner: root
    group: bind
    mode: "0644"
  notify: Restart bind9
  tags: [configure]

- name: Configure MASTER | reverse zone
  ansible.builtin.template:
    src: master/revers.j2
    dest: "/etc/bind/zones/{{ zones.revers }}"
    owner: root
    group: bind
    mode: "0644"
  notify: Restart bind9
  tags: [configure]
