---
- name: Configure SLAVE | named.conf.options
  ansible.builtin.template:
    src: slave/named.conf.options.j2
    dest: "{{ bind_config_path }}/named.conf.options"
    owner: root
    group: "{{ bind_group }}"
    mode: "0644"
  notify: Reload bind
  tags: [configure]

- name: Configure SLAVE | named.conf.local
  ansible.builtin.template:
    src: slave/named.conf.local.j2
    dest: "{{ bind_config_path }}/named.conf.local"
    owner: root
    group: "{{ bind_group }}"
    mode: "0644"
  notify: Reload bind
  tags: [configure]
