---
- name: Reload bind
  ansible.builtin.systemd:
    name: "{{ bind_service_name }}.service"
    state: reloaded
  failed_when: false
  listen: Reload bind

- name: Restart bind
  ansible.builtin.systemd:
    name: "{{ bind_service_name }}.service"
    state: restarted
  listen: Restart bind
